@startuml
'https://plantuml.com/sequence-diagram


interface Movable {
    + int[] coordonnees
    + getCoordonnees(): int[]
}

class Aliment implements Movable {
    + String nom
    + String description
}

class Assiette implements Movable {
    + getAliment(): Aliment
    + setAliment(Aliment): void
}

Aliment --> Assiette : aliment

class Recette extends Aliment {
    + List<Aliment> recettesComposees
    + getIngredients(): Aliment[]
    + setIngredients(Aliment[]): void
}

abstract class DecorateurEtat extends Aliment {
    + toString(): String
    + equals(Object): boolean
    + hashCode(): int
}

Aliment --> DecorateurEtat : composant

class Coupe extends DecorateurEtat {
    + toString(): String
    + equals(Object): boolean
    + hashCode(): int
}

@enduml